Create schema bdValtenis;

USE bdValTennis;

CREATE TABLE tbEstado (

	IDESTADO INT NOT NULL PRIMARY KEY,
    NOMEESTADO VARCHAR (50),
    UF VARCHAR (2),
    PAIS INTEGER

);

CREATE TABLE tbCidade (
	
    IDCIDADE INT NOT NULL PRIMARY KEY,
	NOMECIDADE VARCHAR (50),
    ESTADO INTEGER,
    IDESTADO INT,
    FOREIGN KEY (IDESTADO) REFERENCES tbEstado (IDESTADO)
);

Create TABLE tbCliente(

	IDCLIENTE INT NOT NULL PRIMARY KEY,
    NOME VARCHAR (80) NOT NULL,
    CODIGO VARCHAR (10) NOT NULL,
    CELULAR  VARCHAR (25) NOT NULL,
    ENDERECO VARCHAR (200) NOT NULL,
    EMAIL VARCHAR (80),
    TELEFONE VARCHAR (30) ,
    IDCIDADE INT ,
    FOREIGN KEY (IDCIDADE) REFERENCES tbCidade (IDCIDADE)
);

Create TABLE tbProfissional(

	IDPROFISSIONAL INT NOT NULL PRIMARY KEY,
    NOME VARCHAR (80) NOT NULL,
    CELULAR  VARCHAR (25) NOT NULL,
    ENDERECO VARCHAR (200) NOT NULL,
    EMAIL VARCHAR (80),
    TELEFONE VARCHAR (30) NOT NULL,
    IDCIDADE INT,
    FOREIGN KEY (IDCIDADE) REFERENCES tbCidade (IDCIDADE)
);

CREATE TABLE tbAgendamento(

	IDAGENDAMENTO INT NOT NULL PRIMARY KEY,
    VALOR VARCHAR (10),
    DESCRICAO VARCHAR (500)
);

CREATE TABLE tbUsuario(

	IDUSUSARIO INT NOT NULL PRIMARY KEY,
    SENHA VARCHAR (10) NOT NULL,
    USERNAME VARCHAR (20) NOT NULL

);

CREATE TABLE tbPagamento(
	IdPagamento INT NOT NULL PRIMARY KEY,
	TIPOPAGAMENTO VARCHAR (20) NOT NULL

);

CREATE TABLE tbAgenda (

	IDAGENDA INT NOT NULL PRIMARY KEY,
	DATAHORA DATETIME, 
	OBSERVACAO VARCHAR (500),
    CONFIRMACAO BIT NOT NULL,
    VALOR VARCHAR (5),
    IDCIDADE INT,
    IdPagamento INT,
    IDPROFISSIONAL INT,
    IDAGENDAMENTO INT,
    FOREIGN KEY (IdPagamento) REFERENCES tbPagamento (IdPagamento),
    FOREIGN KEY (IDCIDADE) REFERENCES tbCidade (IDCIDADE),
    FOREIGN KEY (IDAGENDAMENTO) REFERENCES tbAgendamento (IDAGENDAMENTO),
    FOREIGN KEY (IDPROFISSIONAL) REFERENCES tbProfissional (IDPROFISSIONAL)

);
